# Project information
site_name: Kubernetes Networking
site_url: https://ibm.github.io/kubernetes-networking
site_author: IBM Developer

# Repository
repo_name: kubernetes-networking
repo_url: https://github.com/IBM/kubernetes-networking
edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome:
    - About the workshop: README.md
  - Workshop:
    - <b>Lab1 Networking 101</b>:
      - Setup: setup/setup1.md
      - Service Types:
        - Services: services/services.md
        - ClusterIP: services/clusterip.md
        - NodePort: services/nodeport.md
        - Loadbalancer and NLB: services/loadbalancer.md
        - ExternalName: services/externalname.md      
    - <b>Lab2 Ingress</b>:
      - Ingress and ALB: ingress/ingress-alb.md
      - Route: route/route.md
      - Secured Routes: route/secured-routes.md
    - <b>Lab3 Network Policies</b>:
      - Network Policy and Calico: calico/networkpolicy.md
#   - Open Policy Agent (OPA): opa.md
    - <b>Lab4 Create a VPC</b>:
      - Setup: vpc/0_setup.md
      - About: vpc/1_about.md
      - Create a VPC: vpc/2_create_vpc.md
      - Create a Subnet: vpc/3_create_subnet.md
      - Review Security Group: vpc/4_review_security_group.md
      - Create Public Gateway: vpc/5_create_public_gateway.md
      - Review VPC Infrastructure: vpc/6_review_vpc.md
#      - Background:
#        - Load Balancer for VPC: vpc/vpcgen2-loadbalancer.md
#        - Airgap: vpc/airgap.md
    - <b>Lab5 Create a Secure Cluster for VPC</b>:
      - About: vpc_roks/1_create_roks_for_vpc.md
  - References:
    - Contributors: references/contributors.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2020 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: ibm_8bar_reverse_2
  features:
    - navigation.tabs
    #- navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: black
    accent: blue
  custom_dir: overrides

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde